export const Paths: PathsType = {
	adds: '/adds',
	admin: '/admin',
	intro: '/intro',
	member: '/member',
	research: '/research',
	publication: '/publication',
	resource: '/resource',
	paper: '/paper',
	notice: '/notice',
	news: '/news',
	faq: '/faq',
	contact: '/contact',
	login: '/login',
};
