name: Dev CI/CD

on:
  push:
    branches: [develop]

env:
  BRANCH_NAME: develop
  DOCKER_IMAGE: sookyeong/ssk-front
  DOCKER_NAME: ssk-front

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - env:
        ENV_FILE: ${{ secrets.ENV_FILE }}
      run: |
        echo "$ENV_FILE" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  docker_pull_on_server:
    needs: docker_build_and_push
    runs-on: [self-hosted, ssk-front]
    steps:
      - name: Deploy
        run: |
          docker stop ${{ env.DOCKER_NAME }} && docker rm ${{ env.DOCKER_NAME }}
          docker pull ${{ env.DOCKER_IMAGE }}:latest
          docker run -d -p 80:3000 --name ${{ env.DOCKER_NAME }} --restart always ${{ env.DOCKER_IMAGE }}:latest
