name: Prod CI/CD

on:
  push:
    branches: [master]

env:
  BRANCH_NAME: master
  DOCKER_IMAGE: sookyeong/ssk-front-production
  DOCKER_NAME: ssk-front-production

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - env:
          ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
        run: |
          echo "$ENV_FILE" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:ssl
          cache-from: type=gha
          cache-to: type=gha,mode=max

  docker_pull_on_server:
    needs: docker_build_and_push
    runs-on: [self-hosted, ssk-production]
    steps:
      - name: Deploy
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:ssl
